promptToReturnFromSubprocess: false

os:
  overrideGpg: true
  openLink: 'open "$(echo {{link}} | sed ''s/%2F/\//g'')"'
  edit: "nvr --remote-tab-wait +'setl bufhidden=wipe' {{filename}}"
  editAtLine: "nvr --remote-tab-wait +'setl bufhidden=wipe | {{line}}' {{filename}}"
  editAtLineAndWait: "nvr --remote-tab-wait +'setl bufhidden=wipe | {{line}}' {{filename}}"
  openDirInEditor: "nvr --remote-tab-wait +'setl bufhidden=wipe' {{dir}}"

gui:
  filterMode: fuzzy
  nerdFontsVersion: "3"
  border: rounded
  expandFocusedSidePanel: true
  showBottomLine: false
  commandLogSize: 3
  showCommandLog: false

git:
  autoForwardBranches: allBranches
  overrideGpg: true
  branchLogCmd: "git lg {{branchName}}"
  pager:
    externalDiffCommand: difft

customCommands:
  - key: "C"
    command: "npm run commit"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool..."
    subprocess: true
