#!/bin/bash

# Path to the plist file
PLIST=~/Library/Preferences/com.apple.LaunchServices/com.apple.launchservices.secure.plist

# Backup the original plist file
cp "$PLIST" "${PLIST}.backup"

count_ls_handlers() {
	/usr/libexec/PlistBuddy -c "Print :LSHandlers" "$PLIST" | grep "= Dict {" | wc -l | xargs
}

# Get the total number of LSHandlers entries
COUNT=$(count_ls_handlers)
OLD_COUNT=$(count_ls_handlers)

# Loop through the entries and find VSCode entries
for ((i = 0; i < COUNT; i++)); do
	HANDLER=$(/usr/libexec/PlistBuddy -c "Print :LSHandlers:$i:LSHandlerRoleAll" "$PLIST" 2>/dev/null)
	if [ "$HANDLER" == "com.microsoft.vscode" ]; then
		echo "Removing VSCode handler at index $i"
		/usr/libexec/PlistBuddy -c "Delete :LSHandlers:$i" "$PLIST"
		COUNT=$((COUNT - 1)) # Decrease count as the list gets shorter
		i=$((i - 1))         # Decrease index as next item shifts to current index
	fi
done

NEW_COUNT=$(count_ls_handlers)

echo "Operation completed. $((OLD_COUNT - NEW_COUNT)) entries was removed"
