#!/usr/bin/env bash

yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

yabai -m config \
	layout bsp \
	auto_balance on \
	external_bar all:0:40 \
	debug_output off \
	mouse_follows_focus on \
	focus_follows_mouse off \
	window_zoom_persist off \
	insert_feedback_color 0x00ffffff \
	split_ratio 0.5 \
	mouse_modifier fn \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap \
	top_padding 4 \
	bottom_padding 4 \
	left_padding 4 \
	right_padding 4 \
	window_gap 8

# disable specific apps
yabai -m rule --add app="^Pika$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Bartender 5$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Hazel$" manage=off
yabai -m rule --add app="^CleanMyMac X$" manage=off
yabai -m rule --add app="^Outlook$" manage=off
yabai -m rule --add app="^Simulator$" manage=on
yabai -m rule --add app="CleanShot X" manage=off mouse_follows_focus=off

# apply all yabai rules on yabai start to all apps
yabai -m rule --apply
