#!/usr/bin/env bash

simplify_path() {
    echo "${1/#\/Users\/demian/~}"
}

project_folders=(~/Desktop/work ~/Desktop/program-learning)
if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find "${project_folders[@]}" -maxdepth 5 \( -name node_modules -prune -o -name .git -exec dirname {} \; \) | while read -r line; do simplify_path "$line"; done | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
